<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<PropertyGroup>
		<Version>1.3.2-alpha</Version>
		<InformationalVersion>ptree version 1.3.2-alpha</InformationalVersion>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
	</PropertyGroup>

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<PublishAot>true</PublishAot>
		<SelfContained>true</SelfContained>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<InvariantGlobalization>true</InvariantGlobalization>
	</PropertyGroup>



	<ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0" />
  </ItemGroup>

</Project>
